### ISSUE TITLE
[기능추가] 그룹

### ISSUE THREAD

**Issue by hanyiseo2** [Selody-project/.github#7]
### Description
추가되야할 기능으로 여겨지는 것
- 공유페이지 생성하는 사람이 방장 
- group 삭제 (방장만 가능)
- 방장이 다른 user에게 방장 위임
- 사용자가 group 나가기

**Comment by joseph0926** [comment]
확인했습니다!
근데 저희 방장 따로 안정하기로 하지 않았나요?!

**Comment by hyefli-i** [comment]
혹시 그룹 이름 변경 권한에 대해서도 방장에게만 줄까요? 아니면 그 카카오톡에서 개개인이 단톡방 이름을 본인 편의에 맞게 변경할 수 있는 것처럼 그룹 이름 변경이 모두가 가능하도록 하는걸까요?

**Comment by joseph0926** [comment]
> 

방장에게만 주는게 나을거같습니다!

**Comment by hyefli-i** [comment]
그러면 설정 페이지를 조정할 필요가 있겠네요 :) 내일 회의 때 바꾼 부분들에 대해 확인할 수 있도록 기획 수정해놓겠습니다~!

**Comment by joseph0926** [comment]
> 그러면 설정 페이지를 조정할 필요가 있겠네요 :) 내일 회의 때 바꾼 부분들에 대해 확인할 수 있도록 기획 수정해놓겠습니다~!

아 근데 제 개인적인 의견이라,,
내일 회의에서 정해서 다시 확정하는게 좋을거같아요 : )
